name: install Unix environment
description: |
  Install the common environment shared by all jobs in the nix workflow.
runs:
  using: composite
  steps:
    - name: install Python
      uses: ./.github/actions/install-python
    - name: install Ninja on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt install ninja-build
    - name: install Ninja on OSX
      if: runner.os == 'macOS'
      shell: bash
      run: brew install ninja
    - name: check environment
      shell: bash
      run: |
        echo $PATH | tr ':' '\n'
        python --version
        poetry --version
        conan --version
        cmake --version
        ninja --version
        g++ --version
        make --version
        env
