name: test in Unix environment
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu
          - macos
        conan:
          - 1
          - 2
    runs-on: ${{ matrix.platform }}-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: install environment
        uses: ./.github/actions/install-nix
      - name: add Redirectory
        run: |
          conan remote add redirectory https://conan.jfreeman.dev
          # TODO: Possible to authenticate with ${GITHUB_TOKEN}?
      - name: install dependencies
        run: |
          poetry install
      - name: test project
        run: |
          conan export submodules/project-template-cpp/cupcake
          poetry run pytest tests --cov cupcake
          poetry run pytest submodules/project-template-cpp/tests --cov cupcake --cov-append --builder cupcake
